import nivel_0 from '../assets/img/ranking/nivel_0.png'
import nivel_1 from '../assets/img/ranking/nivel_1.png'
import nivel_2 from '../assets/img/ranking/nivel_2.png'
import nivel_3 from '../assets/img/ranking/nivel_3.png'
import nivel_4 from '../assets/img/ranking/nivel_4.png'
import nivel_5 from '../assets/img/ranking/nivel_5.png'
import nivel_6 from '../assets/img/ranking/nivel_6.png'
import nivel_7 from '../assets/img/ranking/nivel_7.png'
import nivel_8 from '../assets/img/ranking/nivel_8.png'
import nivel_9 from '../assets/img/ranking/nivel_9.png'
import nivel_10 from '../assets/img/ranking/nivel_10.png'
import nivel_11 from '../assets/img/ranking/nivel_11.png'
import nivel_12 from '../assets/img/ranking/nivel_12.png'
import nivel_13 from '../assets/img/ranking/nivel_13.png'
import nivel_14 from '../assets/img/ranking/nivel_14.png'
import nivel_15 from '../assets/img/ranking/nivel_15.png'
import nivel_16 from '../assets/img/ranking/nivel_16.png'
import nivel_17 from '../assets/img/ranking/nivel_17.png'
import nivel_18 from '../assets/img/ranking/nivel_18.png'
import nivel_19 from '../assets/img/ranking/nivel_19.png'
import nivel_20 from '../assets/img/ranking/nivel_20.png'
import nivel_21 from '../assets/img/ranking/nivel_21.png'
import nivel_22 from '../assets/img/ranking/nivel_22.png'
import nivel_23 from '../assets/img/ranking/nivel_23.png'
import nivel_24 from '../assets/img/ranking/nivel_24.png'
import nivel_25 from '../assets/img/ranking/nivel_25.png'
import nivel_26 from '../assets/img/ranking/nivel_26.png'
import nivel_27 from '../assets/img/ranking/nivel_27.png'
import nivel_28 from '../assets/img/ranking/nivel_28.png'
import nivel_29 from '../assets/img/ranking/nivel_29.png'
import nivel_30 from '../assets/img/ranking/nivel_30.png'

const niveis = [{ nivel: 0, img: nivel_0, slug: 'Recruta', description: '“Toda grande caminhada começa com um simples passo.”', pontos: 0 }, { nivel: 1, img: nivel_1, slug: 'Soldado', description: '“Ser fraco não é uma opção. É preciso ter disciplina para se tornar o mais forte dos soldados.”', pontos: 15 }, { nivel: 2, img: nivel_2, slug: 'Cabo', description: '“Batalhe pelos seus ideais e faça deles a motivação para as suas conquistas.”', pontos: 40 }, { nivel: 3, img: nivel_3, slug: 'Sagento I', description: '“Não tenha medo de crescer devagar, tenha medo somente de ficar parado.”', pontos: 75 }, { nivel: 4, img: nivel_4, slug: 'Sagento II', description: '“Não será fácil, mas os que conseguirem vencer e persistir provarão ser os mais fortes.”', pontos: 150 }, { nivel: 5, img: nivel_5, slug: 'Sagento III', description: '“Força se adquire com disciplina e foco, ela não vem de uma hora para outra.   ”', pontos: 225 }, { nivel: 6, img: nivel_6, slug: 'Sagento IV', description: '“Mesmo que a jornada seja lenta, abrir mão não acelera.”', pontos: 300 }, { nivel: 7, img: nivel_7, slug: 'Master Sargento I', description: '“Ser uma pessoa melhor é o objetivo do dia.”', pontos: 360 }, { nivel: 8, img: nivel_8, slug: 'Master Sargento II', description: '“A superação da dificuldade depende apenas de você.”', pontos: 420 }, { nivel: 9, img: nivel_9, slug: 'Master Sargento III', description: '“Não importa se o obstáculo é forte, difícil ou grande demais, a persistência para vencer supera qualquer coisa.”', pontos: 480 }, { nivel: 10, img: nivel_10, slug: 'Sagento Major I', description: '“Conforme você superar cada desafio, você sentirá que com motivação e fé nada é impossível de acontecer.”', pontos: 540 }, { nivel: 11, img: nivel_11, slug: 'Sagento Major II', description: '“A sua competição é com você mesmo!”', pontos: 600 }, { nivel: 12, img: nivel_12, slug: 'Sagento Major III', description: '“Você só vai vencer amanhã, se não desistir hoje.”', pontos: 660 }, { nivel: 13, img: nivel_13, slug: 'Aspirante I', description: '“Respire fundo e continue, é proibido desistir.”', pontos: 720 }, { nivel: 14, img: nivel_14, slug: 'Aspirante II', description: '“A força é a nossa característica mais marcantes, mas ela só vem para quem tem foco e disciplina.”', pontos: 780 }, { nivel: 15, img: nivel_15, slug: 'Aspirante III', description: '“Todos os seus amanhã permanecerão iguais a ontem, se você não modificar hoje.”', pontos: 840 }, { nivel: 16, img: nivel_16, slug: 'Tenente I', description: '“Acredite na sua capacidade e conquiste o seu lugar.”', pontos: 900 }, { nivel: 17, img: nivel_17, slug: 'Tenente II', description: '“O que a mente acredita é o que o corpo vai alcançar.”', pontos: 960 }, { nivel: 18, img: nivel_18, slug: 'Tenente III', description: '“Você pode, se acreditar que pode.”', pontos: 1020 }, { nivel: 19, img: nivel_19, slug: 'Capitão I', description: '“Sem mudanças, não existe evolução e crescimento, lembre-se disso.”', pontos: 1080 }, { nivel: 20, img: nivel_20, slug: 'Capitão II', description: '“A constância dos objetivos é o segredo do êxito.”', pontos: 1140 }, { nivel: 21, img: nivel_21, slug: 'Capitão III', description: '“A vitória é um fruto de muita determinação. E não um golpe de sorte.”', pontos: 1200 }, { nivel: 22, img: nivel_22, slug: 'Major I', description: '“É para onde o foco vai que a energia flui.”', pontos: 1260 }, { nivel: 23, img: nivel_23, slug: 'Major II', description: '“Inspiração vem dos outros. Motivação vem de dentro de nós.”', pontos: 1320 }, { nivel: 24, img: nivel_24, slug: 'Major III', description: '“Faça da dificuldade a sua motivação.”', pontos: 1380 }, { nivel: 25, img: nivel_25, slug: 'Coronel I', description: '“Alcançar o que tanto queremos, pode depender apenas de uma pequena dose de coragem.”', pontos: 1440 }, { nivel: 26, img: nivel_26, slug: 'Coronel II', description: '“É o empenho e a persistência que determinam o seu êxito, não a força ou a sorte.”', pontos: 1500 }, { nivel: 27, img: nivel_27, slug: 'General de Divisão', description: '“Os seus resultados são determinados pelas suas atitudes.”', pontos: 1560 }, { nivel: 28, img: nivel_28, slug: 'General de Brigada', description: '“Você sempre vai ser o inimigo mais perigoso que você poderá encontrar”', pontos: 1620 }, { nivel: 29, img: nivel_29, slug: 'General de Exército', description: '“O sucesso é a soma de pequenos esforços repetidos dia após dia.”', pontos: 1650 }, { nivel: 30, img: nivel_30, slug: 'Marechal de Guerra', description: '“A verdadeira vitória de um ser humano não é chegar em primeiro, mas sim nunca desistir.”', pontos: 1830 },]

export default niveis