import nivel_0 from '../assets/img/ranking/nivel_0.png'
import nivel_1 from '../assets/img/ranking/nivel_1.png'
import nivel_2 from '../assets/img/ranking/nivel_2.png'
import nivel_3 from '../assets/img/ranking/nivel_3.png'
import nivel_4 from '../assets/img/ranking/nivel_4.png'
import nivel_5 from '../assets/img/ranking/nivel_5.png'
import nivel_6 from '../assets/img/ranking/nivel_6.png'
import nivel_7 from '../assets/img/ranking/nivel_7.png'
import nivel_8 from '../assets/img/ranking/nivel_8.png'
import nivel_9 from '../assets/img/ranking/nivel_9.png'
import nivel_10 from '../assets/img/ranking/nivel_10.png'
import nivel_11 from '../assets/img/ranking/nivel_11.png'
import nivel_12 from '../assets/img/ranking/nivel_12.png'
import nivel_13 from '../assets/img/ranking/nivel_13.png'
import nivel_14 from '../assets/img/ranking/nivel_14.png'
import nivel_15 from '../assets/img/ranking/nivel_15.png'
import nivel_16 from '../assets/img/ranking/nivel_16.png'
import nivel_17 from '../assets/img/ranking/nivel_17.png'
import nivel_18 from '../assets/img/ranking/nivel_18.png'
import nivel_19 from '../assets/img/ranking/nivel_19.png'
import nivel_20 from '../assets/img/ranking/nivel_20.png'
import nivel_21 from '../assets/img/ranking/nivel_21.png'
import nivel_22 from '../assets/img/ranking/nivel_22.png'
import nivel_23 from '../assets/img/ranking/nivel_23.png'
import nivel_24 from '../assets/img/ranking/nivel_24.png'
import nivel_25 from '../assets/img/ranking/nivel_25.png'
import nivel_26 from '../assets/img/ranking/nivel_26.png'
import nivel_27 from '../assets/img/ranking/nivel_27.png'
import nivel_28 from '../assets/img/ranking/nivel_28.png'
import nivel_29 from '../assets/img/ranking/nivel_29.png'
import nivel_30 from '../assets/img/ranking/nivel_30.png'

const niveis = [{ nivel: 0, img: nivel_0, slug: 'Iniciante', description: '“Você consegue dar o primeiro passo!!”', pontos: 0 }, { nivel: 1, img: nivel_1, slug: 'Nível 1', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 5 }, { nivel: 2, img: nivel_2, slug: 'Nível 2', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 40 }, { nivel: 3, img: nivel_3, slug: 'Nível 3', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 75 }, { nivel: 4, img: nivel_4, slug: 'Nível 4', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 150 }, { nivel: 5, img: nivel_5, slug: 'Nível 5', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 225 }, { nivel: 6, img: nivel_6, slug: 'Nível 6', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 300 }, { nivel: 7, img: nivel_7, slug: 'Nível 7', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 360 }, { nivel: 8, img: nivel_8, slug: 'Nível 8', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 420 }, { nivel: 9, img: nivel_9, slug: 'Nível 9', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 480 }, { nivel: 10, img: nivel_10, slug: 'Nível 10', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 540 }, { nivel: 11, img: nivel_11, slug: 'Nível 11', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 600 }, { nivel: 12, img: nivel_12, slug: 'Nível 12', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 660 }, { nivel: 13, img: nivel_13, slug: 'Nível 13', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 720 }, { nivel: 14, img: nivel_14, slug: 'Nível 14', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 780 }, { nivel: 15, img: nivel_15, slug: 'Nível 15', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 840 }, { nivel: 16, img: nivel_16, slug: 'Nível 16', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 900 }, { nivel: 17, img: nivel_17, slug: 'Nível 17', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 960 }, { nivel: 18, img: nivel_18, slug: 'Nível 18', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 1020 }, { nivel: 19, img: nivel_19, slug: 'Nível 19', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 1080 }, { nivel: 20, img: nivel_20, slug: 'Nível 20', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 1140 }, { nivel: 21, img: nivel_21, slug: 'Nível 21', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 1200 }, { nivel: 22, img: nivel_22, slug: 'Nível 22', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 1260 }, { nivel: 23, img: nivel_23, slug: 'Nível 23', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 1320 }, { nivel: 24, img: nivel_24, slug: 'Nível 24', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 1380 }, { nivel: 25, img: nivel_25, slug: 'Nível 25', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 1440 }, { nivel: 26, img: nivel_26, slug: 'Nível 26', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 1500 }, { nivel: 27, img: nivel_27, slug: 'Nível 27', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 1560 }, { nivel: 28, img: nivel_28, slug: 'Nível 28', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 1620 }, { nivel: 29, img: nivel_29, slug: 'Nível 29', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 1680 }, { nivel: 30, img: nivel_30, slug: 'Nível 30', description: '“Toda grande caminhada começa com um simples passo!”', pontos: 1825 },]


export default niveis